Repository karim-agha5/Shopify, pull requests merged in 2023-06, with the labels that each got.

#2 add splash and onboarding
  app/build.gradle
  app/src/main/java/com/example/shopify/features/home/view/MainActivity.kt
  app/src/main/java/com/example/shopify/features/onboarding/OnboardingFragment.kt
  app/src/main/java/com/example/shopify/features/onboarding/ViewPagerAdapter.kt
  app/src/main/java/com/example/shopify/features/onboarding/view/FirstFragment.kt
  app/src/main/java/com/example/shopify/features/onboarding/view/SecondFragment.kt
  app/src/main/java/com/example/shopify/features/onboarding/view/ThirdFragment.kt
  app/src/main/java/com/example/shopify/features/splash/SplashFragment.kt
  app/src/main/res/drawable/checkout.png
  app/src/main/res/drawable/online_shop.png
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/shopping_cart.png
  app/src/main/res/font/amiri_bold.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/layout/fragment_third.xml
  app/src/main/res/layout/onboarding.xml
  app/src/main/res/layout/splash_screen.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/raw/loading.json
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  github.properties
  gradle.properties
  settings.gradle
Labels: enhancement

#11 Feature/ads impl
  app/build.gradle
  app/src/main/java/com/example/shopify/core/common/data/model/Promocode.kt
  app/src/main/java/com/example/shopify/core/util/Constants.kt
  app/src/main/java/com/example/shopify/features/home/view/AdImagesAdapter.kt
  app/src/main/java/com/example/shopify/features/home/view/ui/home/HomeFragment.kt
  app/src/main/res/drawable/custom_dialog_shape.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/ad_item_layout.xml
  app/src/main/res/layout/brand_card.xml
  app/src/main/res/layout/custom_dialog_layout.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_notifications.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#15 add toolbar
  app/src/main/java/com/example/shopify/features/home/view/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#14 add initial settings screen ui
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/shopify/core/common/data/remote/retrofit/RetrofitHelper.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/data/RemoteCurrenciesService.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/data/remote/IRemoteCurrenciesSource.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/data/remote/RemoteCurrenciesSourceImpl.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/data/repository/CurrencyRepositoryImpl.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/data/repository/IRemoteCurrencyRepository.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/model/response/RemoteCurrenciesResponse.kt
  app/src/main/java/com/example/shopify/core/common/features/currency/model/response/RemoteCurrency.kt
  app/src/main/java/com/example/shopify/core/common/mappers/CurrencyMapper.kt
  app/src/main/java/com/example/shopify/core/util/Constants.kt
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/home/network/RetrofitClient.kt
  app/src/main/java/com/example/shopify/features/map/view/MapBottomNavigationSheet.kt
  app/src/main/java/com/example/shopify/features/map/view/MapFragment.kt
  app/src/main/java/com/example/shopify/features/settings/model/CurrencyUiState.kt
  app/src/main/java/com/example/shopify/features/settings/view/SettingsFragment.kt
  app/src/main/java/com/example/shopify/features/settings/viewmodel/SettingsViewModel.kt
  app/src/main/java/com/example/shopify/features/settings/viewmodel/SettingsViewModelFactory.kt
  app/src/main/res/drawable/baseline_add_location_alt_24.xml
  app/src/main/res/drawable/baseline_arrow_back_36.xml
  app/src/main/res/drawable/baseline_check_36.xml
  app/src/main/res/drawable/baseline_close_36.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/map_modal_bottom_navigation_sheet_content.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/menu/settings_fragment_menu.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: enhancement

#20 Feature/authentication logic
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerRegistration.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerRegistrationAddress.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerRegistrationInfo.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerResponse.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerResponseAddress.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerResponseInfo.kt
  app/src/main/java/com/example/shopify/core/common/data/model/ErrorDetails.kt
  app/src/main/java/com/example/shopify/core/common/data/model/ErrorResponse.kt
  app/src/main/java/com/example/shopify/core/common/data/remote/retrofit/RetrofitHelper2.kt
  app/src/main/java/com/example/shopify/core/common/data/remote/retrofit/RetrofitStub.kt
  app/src/main/java/com/example/shopify/core/common/interfaces/IMainRemoteDataSource.kt
  app/src/main/java/com/example/shopify/core/common/interfaces/IShopifyService.kt
  app/src/main/java/com/example/shopify/core/util/ApiState2.kt
  app/src/main/java/com/example/shopify/core/util/Constants.kt
  app/src/main/java/com/example/shopify/features/authentication/login/view/LoginFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/shopify/features/authentication/login/viewmodel/LoginViewModelFactory.kt
  app/src/main/java/com/example/shopify/features/authentication/login/viewmodel/LoginViewModelStub.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/IRegistrationRepository.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/RegistrationRepository.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/IRemoteRegisterationRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/IRemoteRegistrationRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/RemoteRegistrationRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/view/RegistrationFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegisterationViewModelStub.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegistrationViewModel.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegistrationViewModelFactory.kt
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_registration.xml
  app/src/main/res/navigation/main_graph.xml
  build.gradle
Labels: enhancement

#21 update-layouts-problems
  app/src/main/java/com/example/shopify/features/authentication/login/view/LoginFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/view/RegistrationFragment.kt
  app/src/main/java/com/example/shopify/features/home/view/ui/home/HomeFragment.kt
  app/src/main/java/com/example/shopify/features/splash/SplashFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_splash.xml
Labels: bug

#23 add shopping cart ui
  app/src/main/java/com/example/shopify/features/shoppingcart/model/Order.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/OrderItemsAdapter.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  app/src/main/res/drawable/baseline_add_24.xml
  app/src/main/res/drawable/baseline_more_vert_24.xml
  app/src/main/res/drawable/baseline_remove_24.xml
  app/src/main/res/layout/fragment_shopping_cart.xml
  app/src/main/res/layout/order_item_layout.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#24 Bugfix/error msg registration
  app/src/main/java/com/example/shopify/features/authentication/registration/view/RegistrationFragment.kt
  app/src/main/java/com/example/shopify/features/onboarding/OnboardingFragment.kt
  app/src/main/res/layout/fragment_onboarding.xml
  app/src/main/res/layout/onboarding.xml
  app/src/main/res/navigation/main_graph.xml
Labels: bug

#25 Orders branch2
  app/src/main/java/com/example/shopify/features/me/view/ui/me/ProfileFragment.kt
  app/src/main/java/com/example/shopify/features/products/view/ui/products/ProductsFragment.kt
  app/src/main/res/drawable/baseline_arrow_forward_ios_24.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#26 Feature/product details
  app/build.gradle
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerFirebase.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerId.kt
  app/src/main/java/com/example/shopify/core/common/data/model/CustomerResponseInfo.kt
  app/src/main/java/com/example/shopify/core/common/data/model/Discount.kt
  app/src/main/java/com/example/shopify/core/common/data/model/DiscountRegistration.kt
  app/src/main/java/com/example/shopify/core/common/data/model/DraftOrder.kt
  app/src/main/java/com/example/shopify/core/common/data/model/DraftOrderBody.kt
  app/src/main/java/com/example/shopify/core/common/data/model/DraftOrderRegistration.kt
  app/src/main/java/com/example/shopify/core/common/data/model/DraftOrderResponse.kt
  app/src/main/java/com/example/shopify/core/common/data/model/LineItem.kt
  app/src/main/java/com/example/shopify/core/common/data/model/LineItemRegistration.kt
  app/src/main/java/com/example/shopify/core/common/data/remote/IRemoteDataSource.kt
  app/src/main/java/com/example/shopify/core/common/data/remote/retrofit/RetrofitHelper2.kt
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/authentication/login/LoginStub.kt
  app/src/main/java/com/example/shopify/features/authentication/login/view/LoginFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/RegisterationStub.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/IRegistrationRepository.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/RegistrationRepository.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/CreationDraftOrderRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/ICreationDraftOrderRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/IRegistrationRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/RegistrationRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/retrofit/IShopifyDraftOrderApi.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/retrofit/IShopifyRegistrationApi.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/view/RegistrationFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegistrationViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#29 Feature/shopping cart impl
  app/src/main/java/com/example/shopify/features/home/view/ui/home/HomeFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/OrderItemsAdapter.kt
  app/src/main/res/layout/fragment_shopping_cart.xml
  app/src/main/res/menu/order_item_menu.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#30 solve-firebase-sync
  app/src/main/java/com/example/shopify/core/common/features/draftorder/data/DraftOrderRepositoryImpl.kt
  app/src/main/java/com/example/shopify/features/authentication/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/view/RegistrationFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegistrationViewModel.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegistrationViewModelFactory.kt
  app/src/main/java/com/example/shopify/features/home/HomeStub.kt
  app/src/main/res/navigation/main_graph.xml
Labels: bug

#36 add user model info to shopping cart
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/authentication/login/view/LoginFragment.kt
  app/src/main/java/com/example/shopify/features/checkout/view/CheckoutFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/OrderItemsAdapter.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  app/src/main/res/layout/fragment_checkout.xml
  app/src/main/res/layout/fragment_shopping_cart.xml
  app/src/main/res/layout/shopping_cart_not_signed_layout.xml
  app/src/main/res/navigation/main_graph.xml
Labels: enhancement

#38 add checkout ui
  app/src/main/java/com/example/shopify/features/checkout/view/CheckoutFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/model/PreplacedOrder.kt
  app/src/main/res/drawable/cash_on_delivery.png
  app/src/main/res/drawable/credit_card.png
  app/src/main/res/layout/fragment_checkout.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#39 Feature/product details UI
  app/build.gradle
  app/src/main/java/com/example/shopify/features/product_details/interfaces/OnImageCardClickListener.kt
  app/src/main/java/com/example/shopify/features/product_details/interfaces/OnImageSlideListener.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductDetailsFragment.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductImagesAdapter.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductSizesAdapter.kt
  app/src/main/res/drawable/baseline_back_arrow_24.xml
  app/src/main/res/drawable/baseline_circle_red_24.xml
  app/src/main/res/drawable/baseline_circle_white_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_product_details.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/product_details_image_card.xml
  app/src/main/res/layout/product_size_card.xml
  app/src/main/res/mipmap-hdpi/empty.png
  app/src/main/res/mipmap-hdpi/placeholder.png
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle.properties
  settings.gradle
Labels: enhancement

#42 Feature/product details logic
  app/src/main/java/com/example/shopify/core/common/data/local/firebase/FirebaseDataManager.kt
  app/src/main/java/com/example/shopify/core/common/data/local/room/RoomStub.kt
  app/src/main/java/com/example/shopify/core/common/data/model/Product.kt
  app/src/main/java/com/example/shopify/core/common/features/draftorder/data/DraftOrderRepositoryImpl.kt
  app/src/main/java/com/example/shopify/core/common/features/draftorder/model/modification/request/ModifyDraftOrderRequestLineItem.kt
  app/src/main/java/com/example/shopify/core/common/mappers/ProductMapper.kt
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/authentication/login/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/CreationDraftOrderRemoteSource.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/data/remote/IShopifyDraftOrderApi.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/viewmodel/RegistrationViewModel.kt
  app/src/main/java/com/example/shopify/features/category/view/ui/category/CategoryFragment.kt
  app/src/main/java/com/example/shopify/features/home/view/ui/home/HomeFragment.kt
  app/src/main/java/com/example/shopify/features/me/view/ui/me/ProfileFragment.kt
  app/src/main/java/com/example/shopify/features/orders/view/OrdersFragment.kt
  app/src/main/java/com/example/shopify/features/product_details/interfaces/OnVariantSelection.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductDetailsFragment.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductSizesAdapter.kt
  app/src/main/java/com/example/shopify/features/product_details/viewmodel/ProductDetailsViewModel.kt
  app/src/main/java/com/example/shopify/features/product_details/viewmodel/ProductDetailsViewModelFactory.kt
  app/src/main/java/com/example/shopify/features/products/view/ui/products/ProductsFragment.kt
  app/src/main/java/com/example/shopify/features/settings/view/SettingsFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  app/src/main/java/com/example/shopify/features/splash/SplashFragment.kt
  app/src/main/res/layout/dialog_login.xml
  app/src/main/res/layout/dialog_success.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_product_details.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/raw/question.json
  app/src/main/res/raw/success.json
  app/src/main/res/values/strings.xml
Labels: enhancement

#43 add successful checkout screen impl
  app/src/main/java/com/example/shopify/core/util/Constants.kt
  app/src/main/java/com/example/shopify/features/checkout/view/CheckoutFragment.kt
  app/src/main/java/com/example/shopify/features/home/view/ui/home/HomeFragment.kt
  app/src/main/java/com/example/shopify/features/orders_details/view/OrdersDetailsAdapter.kt
  app/src/main/java/com/example/shopify/features/orders_details/view/OrdersDetailsFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/SuccessfulCheckoutFragment.kt
  app/src/main/res/drawable/successful_checkout.png
  app/src/main/res/layout/fragment_checkout.xml
  app/src/main/res/layout/fragment_successful_checkout.xml
  app/src/main/res/layout/successful_checkout_dialog.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/raw/loading_to_successful_checkout.json
  app/src/main/res/raw/successful_checkout_animation.json
  app/src/main/res/values/strings.xml
Labels: enhancement

#44 Feature/product details logic addition
  app/src/main/java/com/example/shopify/core/common/data/model/Property.kt
  app/src/main/java/com/example/shopify/core/common/features/draftorder/model/modification/request/ModifyDraftOrderRequestLineItem.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductDetailsFragment.kt
  app/src/main/java/com/example/shopify/features/product_details/viewmodel/ProductDetailsViewModel.kt
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#48 fix-bottom-nav-bar
  app/src/main/res/drawable/category_filled_icon.png
  app/src/main/res/drawable/category_outlined_icon.png
  app/src/main/res/drawable/home_filled_icon.png
  app/src/main/res/drawable/home_outline_icon.png
  app/src/main/res/drawable/selector_cart_icon.xml
  app/src/main/res/drawable/selector_category_icon.xml
  app/src/main/res/drawable/selector_home_icon.xml
  app/src/main/res/drawable/selector_user_icon.xml
  app/src/main/res/drawable/shopping_cart_filled_icon.png
  app/src/main/res/drawable/shopping_cart_outlined_icon.png
  app/src/main/res/drawable/user_filled_icon.png
  app/src/main/res/drawable/user_outlined_icon.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_nav_menu.xml
Labels: bug

#49 Feature/checkout impl
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/shopify/core/util/Constants.kt
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/model/EphemeralKey.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/model/StripeCustomer.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/model/StripeCustomerResponse.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/model/StripePaymentIntentResponse.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/remote/IStripeRemoteSource.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/remote/StripeRemoteSourceImpl.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/service/StripeRetrofitHelper.kt
  app/src/main/java/com/example/shopify/features/checkout/paymentgateway/stripe/service/StripeService.kt
  app/src/main/java/com/example/shopify/features/checkout/view/CheckoutFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  gradle.properties
Labels: enhancement

#50 Feature/shopping cart impl
  app/src/main/java/com/example/shopify/core/common/features/draftorder/data/DraftOrderRepositoryImpl.kt
  app/src/main/java/com/example/shopify/core/common/features/draftorder/model/modification/request/ModifyDraftOrderRequestLineItem.kt
  app/src/main/java/com/example/shopify/core/common/features/draftorder/model/modification/response/ModifyDraftOrderResponseBody.kt
  app/src/main/java/com/example/shopify/core/common/mappers/ProductMapper.kt
  app/src/main/java/com/example/shopify/features/checkout/view/CheckoutFragment.kt
  app/src/main/java/com/example/shopify/features/checkout/view/SuccessfulCheckoutFragment.kt
  app/src/main/java/com/example/shopify/features/product_details/view/ProductDetailsFragment.kt
  app/src/main/java/com/example/shopify/features/product_details/viewmodel/ProductDetailsViewModel.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/domain/DraftOrder.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/OrderItemsAdapter.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/interfaces/CartOrderItemHandler.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/interfaces/TotalAmountHandler.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/viewmodel/ShoppingCartListItemsViewModel.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/viewmodel/factory/ShoppingCartItemViewModelFactory.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/viewmodel/factory/ShoppingCartListItemsViewModelFactory.kt
  app/src/main/res/drawable/empty_cart.png
  app/src/main/res/layout/add_to_cart_custom_dialog_failure.xml
  app/src/main/res/layout/fragment_shopping_cart.xml
  app/src/main/res/layout/fragment_successful_checkout.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/raw/empty_cart_animation.json
  app/src/main/res/raw/failure_animation.json
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#52 add datastore impl and settings
  app/build.gradle
  app/src/main/java/com/example/shopify/core/common/features/usersettings/UserSettingsDataStore.kt
  app/src/main/java/com/example/shopify/core/util/Constants.kt
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/authentication/login/view/LoginFragment.kt
  app/src/main/java/com/example/shopify/features/authentication/registration/view/RegistrationFragment.kt
  app/src/main/java/com/example/shopify/features/settings/view/SettingsFragment.kt
  app/src/main/java/com/example/shopify/features/splash/SplashFragment.kt
  dfdsf
Labels: enhancement

#56 Bugfix/npe
  app/src/main/java/com/example/shopify/core/common/data/model/Product.kt
  app/src/main/java/com/example/shopify/core/common/mappers/ProductMapper.kt
  app/src/main/java/com/example/shopify/features/orders/model/model_response/LineItem.kt
  app/src/main/java/com/example/shopify/features/orders/model/model_response/OrderResponseData.kt
  app/src/main/java/com/example/shopify/features/orders/view/OrdersAdapter.kt
  app/src/main/java/com/example/shopify/features/orders_details/view/OrdersDetailsAdapter.kt
  app/src/main/java/com/example/shopify/features/orders_details/view/OrdersDetailsFragment.kt
  app/src/main/java/com/example/shopify/features/products/repository/IProductsRepository.kt
  app/src/main/java/com/example/shopify/features/products/repository/ProductsRepository.kt
  app/src/main/java/com/example/shopify/features/products/view/ui/products/ProductsAdapter.kt
  app/src/main/java/com/example/shopify/features/products/view/ui/products/ProductsFragment.kt
  app/src/main/java/com/example/shopify/features/products/view/ui/products/ProductsViewModel.kt
  app/src/main/java/com/example/shopify/features/search/viewmodel/SearchViewModel.kt
  app/src/main/java/com/example/shopify/features/shoppingcart/view/ShoppingCartFragment.kt
  fd
Labels: bug

#57 Feature/settings datastore
  app/src/main/java/com/example/shopify/core/common/features/usersettings/UserSettingsDataStore.kt
  app/src/main/java/com/example/shopify/features/MainActivity.kt
  app/src/main/java/com/example/shopify/features/settings/view/SettingsFragment.kt
Labels: bug
